version: "3.9"
services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  postgres:
    container_name: postgres_container
    image: postgres:13.3
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: nestjs_main
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: 123123123
  redis:
      image: redis:alpine3.16
      container_name: redis-wsbe
      env_file: .env
      command: >
        --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
      ports:
        - "6379:6379"
      restart: unless-stopped

  nats:
    image: nats:alpine3.17
    container_name: nats-main
    env_file:
      - .env
    environment:
      NATS_SERVERS: ${NATS_SERVERS}
      NATS_USERNAME: ${NATS_USERNAME}
      NATS_PASSWORD: ${NATS_PASSWORD}
    command: "--js -m 8009"
    volumes:
      - ./data:/data
    ports:
      - "4222:${NATS_PORT}"
      - "8009:8009"

volumes:
  minio_storage:
  postgres_data:
  redis_data:

